In [77]:
import pandas as pd
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_US.csv'
df = pd.read_csv(url, error_bad_lines=False)

#remove cols
df = df.drop(columns = ['iso2', 'iso3', 'code3', 'FIPS', 'Country_Region', 'Combined_Key'])
df = df.rename(columns={"Admin2": "County", 'Province_State':'State', 'Long_':'Long'})

#MOST POPULOUS COUNTIES IN U.S. by contintental states
lyst = []
for x in df['State']:
    df2 = df[(df['State'] == x)]
    df3 = df2[(df2['Population'] == df2['Population'].max())]
    uid = df3.iat[0,0]
    lyst.append(uid)
    
    
df = df[df['UID'].isin(lyst)]
     
#remove hawaii & DC
df = df[(df['State'] != 'Hawaii')]
df = df[(df['State'] != 'District of Columbia')]
df = df[(df['State'] != 'Puerto Rico')]
df = df[(df['State'] != 'Alaska')]
df = df[(df['State'] != 'American Samoa')]
df = df[(df['State'] != 'Diamond Princess')]
df = df[(df['State'] != 'Alaska')]
df = df[(df['State'] != 'Northern Mariana Islands')]
df = df[(df['State'] != 'Virgin Islands')]
df = df[(df['State'] != 'Guam')]
df = df[(df['State'] != 'Grand Princess')]


df = df.reset_index(drop = True)
df

,UID,County,State,Lat,Long,Population,1/22/20,1/23/20,1/24/20,1/25/20,...,3/7/22,3/8/22,3/9/22,3/10/22,3/11/22,3/12/22,3/13/22,3/14/22,3/15/22,3/16/22
0,84001073,Jefferson,Alabama,33.555547,-86.895063,658573,0,0,0,0,...,2244,2247,2248,2253,2263,2263,2263,2271,2280,2281
1,84004013,Maricopa,Arizona,33.348359,-112.491815,4485414,0,0,0,0,...,15625,15625,15855,15855,15855,15855,15855,15855,15855,16166
2,84005119,Pulaski,Arkansas,34.770541,-92.313551,391911,0,0,0,0,...,1134,1140,1142,1143,1144,1146,1148,1150,1152,1154
3,84006037,Los Angeles,California,34.308284,-118.228241,10039107,0,0,0,0,...,31046,31084,31138,31178,31225,31275,31275,31315,31343,31372
4,84008031,Denver,Colorado,39.760183,-104.872569,727211,0,0,0,0,...,1274,1275,1275,1275,1275,1275,1275,1278,1278,1278
5,84009001,Fairfield,Connecticut,41.268099,-73.388117,943332,0,0,0,0,...,2645,2653,2662,2663,2668,2668,2668,2668,2673,2673
6,84010003,New Castle,Delaware,39.579926,-75.640550,558753,0,0,0,0,...,1338,1338,1338,1338,1338,1338,1367,1367,1368,1368
7,84012086,Miami-Dade,Florida,25.611236,-80.551706,2716940,0,0,0,0,...,10320,10320,10320,10320,10320,10320,10320,10643,10643,10643
8,84013121,Fulton,Georgia,33.792169,-84.463194,1063937,0,0,0,0,...,2160,2167,2170,2179,2182,2182,2182,2191,2191,2193
9,84016001,Ada,Idaho,43.452658,-116.241552,481587,0,0,0,0,...,992,992,995,996,997,997,997,997,997,998
10,84017031,Cook,Illinois,41.841448,-87.816588,5150233,0,0,0,0,...,14123,14131,14142,14156,14163,14163,14163,14173,14185,14191
11,84018097,Marion,Indiana,39.781636,-86.138263,964582,0,0,0,0,...,2827,2828,2837,2838,2839,2839,2839,2840,2841,2846
12,84019153,Polk,Iowa,41.686795,-93.577675,490161,0,0,0,0,...,1053,1053,1066,1066,1066,1066,1066,1066,1066,1076
13,84020091,Johnson,Kansas,38.885482,-94.822509,602401,0,0,0,0,...,1176,1176,1182,1182,1181,1181,1181,1181,1181,1185
14,84021111,Jefferson,Kentucky,38.186647,-85.659310,766757,0,0,0,0,...,2091,2091,2091,2109,2109,2109,2109,2109,2109,2109
15,84022033,East Baton Rouge,Louisiana,30.538420,-91.097776,440059,0,0,0,0,...,1316,1316,1317,1321,1324,1324,1324,1324,1325,1325
16,84023005,Cumberland,Maine,43.837075,-70.372270,295003,0,0,0,0,...,341,341,341,341,343,343,343,343,343,343
17,84024031,Montgomery,Maryland,39.136763,-77.203582,1050688,0,0,0,0,...,2001,2002,2005,2005,2005,2006,2006,2007,2007,2009
18,84025017,Middlesex,Massachusetts,42.486077,-71.390492,1611699,0,0,0,0,...,4697,4714,4718,4723,4726,4726,4726,3928,3931,3930
19,84026163,Wayne,Michigan,42.280984,-83.281255,1749343,0,0,0,0,...,7713,7713,7760,7760,7772,7772,7772,7775,7775,7806
20,84027053,Hennepin,Minnesota,45.007615,-93.476949,1265843,0,0,0,0,...,2516,2521,2526,2530,2532,2532,2532,2535,2536,2539
21,84028049,Hinds,Mississippi,32.265628,-90.444354,231840,0,0,0,0,...,772,775,775,775,775,775,775,781,781,781
22,84029189,St. Louis,Missouri,38.637700,-90.445837,994205,0,0,0,0,...,3214,3218,3221,3222,3223,3223,3223,3224,3224,3222
23,84030111,Yellowstone,Montana,45.939559,-108.269149,161300,0,0,0,0,...,534,535,535,538,539,539,539,539,539,540
24,84031055,Douglas,Nebraska,41.295183,-96.150853,571327,0,0,0,0,...,718,718,718,718,718,718,718,718,718,718
25,84032003,Clark,Nevada,36.214589,-115.013024,2266715,0,0,0,0,...,7570,7591,7617,7633,7653,7653,7653,7653,7653,7673
26,84033011,Hillsborough,New Hampshire,42.915378,-71.720025,417025,0,0,0,0,...,883,884,884,885,885,885,886,887,887,889
27,84034003,Bergen,New Jersey,40.960109,-74.071643,932202,0,0,0,0,...,3405,3408,3408,3409,3410,3411,3412,3413,3414,3414
28,84035001,Bernalillo,New Mexico,35.051636,-106.670355,679121,0,0,0,0,...,1664,1672,1675,1679,1683,1683,1683,1698,1705,1711
29,84036047,Kings,New York,40.636182,-73.949356,2559903,0,0,0,0,...,12732,12740,12734,12737,12739,12739,12747,12747,12757,12763
30,84037183,Wake,North Carolina,35.788793,-78.652492,1111761,0,0,0,0,...,1031,1032,1032,1036,1036,1036,1036,1036,1036,1036
31,84038017,Cass,North Dakota,46.932017,-97.244472,181923,0,0,0,0,...,330,331,331,332,332,332,332,332,332,332
32,84039049,Franklin,Ohio,39.969958,-83.011158,1316756,0,0,0,0,...,2510,2510,2510,2510,2510,2510,2510,2510,2510,2510
33,84040109,Oklahoma,Oklahoma,35.551401,-97.407169,797434,0,0,0,0,...,2272,2272,2272,2301,2301,2301,2301,2301,2301,2301
34,84041051,Multnomah,Oregon,45.547480,-122.416935,812855,0,0,0,0,...,1069,1074,1079,1094,1098,1098,1098,1099,1102,1105
35,84042101,Philadelphia,Pennsylvania,40.003385,-75.137927,1584064,0,0,0,0,...,5002,5010,5013,5015,5018,5019,5019,5020,5025,5031
36,84044007,Providence,Rhode Island,41.870647,-71.577535,638931,0,0,0,0,...,2449,2449,2453,2453,2453,2453,2453,2453,2453,2458
37,84045045,Greenville,South Carolina,34.895023,-82.372950,523542,0,0,0,0,...,1926,1928,1928,1940,1941,1941,1941,1941,1941,1941
38,84046099,Minnehaha,South Dakota,43.674416,-96.791089,193134,0,0,0,0,...,503,505,505,505,505,505,505,506,506,507
39,84047157,Shelby,Tennessee,35.186478,-89.896924,937166,0,0,0,0,...,3151,3151,3178,3178,3178,3178,3178,3178,3178,3219
40,84048201,Harris,Texas,29.858649,-95.393395,4713325,0,0,0,0,...,10724,10738,10747,10757,10769,10777,10783,10784,10791,10801
41,84049035,Salt Lake,Utah,40.666165,-111.921601,1160437,0,0,0,0,...,1560,1569,1572,1576,1581,1581,1581,1584,1587,1588
42,84050007,Chittenden,Vermont,44.463228,-73.083592,163774,0,0,0,0,...,158,159,159,159,159,159,159,159,159,159
43,84051059,Fairfax,Virginia,38.836776,-77.275658,1147532,0,0,0,0,...,1384,1393,1393,1398,1401,1401,1401,1411,1414,1414
44,84053033,King,Washington,47.491379,-121.834613,2252782,0,0,0,0,...,2561,2561,2576,2576,2588,2588,2588,2599,2599,2599
45,84054039,Kanawha,West Virginia,38.338601,-81.528571,178124,0,0,0,0,...,684,686,690,692,693,693,693,692,698,698
46,84055079,Milwaukee,Wisconsin,43.004861,-87.967332,945726,0,0,0,0,...,2126,2134,2143,2152,2160,2160,2160,2170,2181,2192
47,84056021,Laramie,Wyoming,41.307025,-104.688750,99500,0,0,0,0,...,278,279,279,279,279,279,279,279,283,283

In [78]:
#for one
#Autuga
#create empty df
column_names = ["Date", "Deaths", "County", "State", "Lat", "Long", "Population"]
data = pd.DataFrame(columns = column_names)


#loop
for x in df['UID']:
    df2 = df[(df['UID'] == x)]


    df2 = df2.T
    #reset col names
    df2.columns = range(df2.shape[1])
    
    df2['UID'] = df2.iloc[0,0]
    df2['County'] = df2.iloc[1,0]
    df2['State'] = df2.iloc[2,0]
    df2['Lat'] = df2.iloc[3,0]
    df2['Long'] = df2.iloc[4,0]
    df2['Population'] = df2.iloc[5,0]
    
    #outside loop
    #remove top 5

    df2 = df2.iloc[6:]

    df2 = df2.reset_index()

    #rename cols
    df2 = df2.rename(columns={"index":"Date", 0:"Deaths"})
    
    df2['New Deaths'] = df2.Deaths.diff().fillna(0)
    
    #FIX NEW Deaths
    df2['New Deaths']=df2['New Deaths'].mask(df2['New Deaths'].lt(0),0)

    df2['Deaths'] = df2['New Deaths'].cumsum()

    
    data = data.append(df2, True)
    
#change to date time
data['Date'] = pd.to_datetime(data.Date)
data['Date'] = data['Date'].dt.strftime('%Y-%m-%d')
#round to 6dp
data.Lat = data.Lat.round(decimals=6)
data.Long = data.Long.round(decimals=6)


data

,Date,Deaths,County,State,Lat,Long,Population,UID,New Deaths
0,2020-01-22,0,Jefferson,Alabama,33.555547,-86.895063,658573,84001073.0,0.0
1,2020-01-23,0,Jefferson,Alabama,33.555547,-86.895063,658573,84001073.0,0.0
2,2020-01-24,0,Jefferson,Alabama,33.555547,-86.895063,658573,84001073.0,0.0
3,2020-01-25,0,Jefferson,Alabama,33.555547,-86.895063,658573,84001073.0,0.0
4,2020-01-26,0,Jefferson,Alabama,33.555547,-86.895063,658573,84001073.0,0.0
...,...,...,...,...,...,...,...,...,...
37675,2022-03-12,279,Laramie,Wyoming,41.307025,-104.688750,99500,84056021.0,0.0
37676,2022-03-13,279,Laramie,Wyoming,41.307025,-104.688750,99500,84056021.0,0.0
37677,2022-03-14,279,Laramie,Wyoming,41.307025,-104.688750,99500,84056021.0,0.0
37678,2022-03-15,283,Laramie,Wyoming,41.307025,-104.688750,99500,84056021.0,4.0
37679,2022-03-16,283,Laramie,Wyoming,41.307025,-104.688750,99500,84056021.0,0.0

In [79]:
# weather----------------------------
#import
dfweather = pd.read_csv("weather2.csv")

#pick

#rename
dfweather = dfweather.rename(columns={"datetime":"Date"})

#split
dfsplit = dfweather['name'].str.split(',', expand=True)

#drop name from
dfweather = dfweather.drop(columns = ['name'])


#rename split
dfsplit = dfsplit.rename(columns={0:"Lat", 1:"Long"})


#CONCAT
dfw = pd.concat([dfsplit, dfweather], axis=1)

#convert date
dfw['Date'] = pd.to_datetime(dfw.Date)
dfw['Date'] = dfw['Date'].dt.strftime('%Y-%m-%d')
dfw['Date']=dfw['Date'].astype(object)

#convert lat, long to floats
dfw['Lat']=dfw['Lat'].astype(float)
dfw['Long']=dfw['Long'].astype(float)


#pcik cols
dfw = dfw[['Lat', 'Long', 'Date', 'temp', 'humidity', 'windspeed']]

#round
dfw.Lat = dfw.Lat.round(decimals=6)
dfw.Long = dfw.Long.round(decimals=6)


dfw

             Lat       Long        Date  temp  humidity  windspeed
0      42.486077 -71.390492  2020-03-01  -3.9     46.16       25.3
1      42.486077 -71.390492  2020-03-02   4.1     55.49       27.2
2      42.486077 -71.390492  2020-03-03  12.1     61.61       24.7
3      42.486077 -71.390492  2020-03-04   8.0     49.14       40.6
4      42.486077 -71.390492  2020-03-05   5.5     45.23       30.6
...          ...        ...         ...   ...       ...        ...
35035  40.003385 -75.137927  2022-02-24   0.7     53.20       20.3
35036  40.003385 -75.137927  2022-02-25   2.9     75.00       28.5
35037  40.003385 -75.137927  2022-02-26   0.3     49.80       16.5
35038  40.003385 -75.137927  2022-02-27   3.5     47.10       30.2
35039  40.003385 -75.137927  2022-02-28   1.2     38.90       21.5

[35040 rows x 6 columns]

In [80]:
#join
#dfnew = reduce(lambda left,right: pd.merge(left,right,on='GrowingSeason'), dfs)

dfnew = pd.merge(data, dfw, on=['Lat', 'Long', 'Date'])

#sort
new_cols = ['UID',"Date","County","State","Population","Lat", 'Long', 'temp', 'humidity', 'windspeed', 'New Deaths','Deaths']
dfnew=dfnew[new_cols]
dfnew=dfnew.reindex(columns=new_cols)
dfnew['New Deaths']=dfnew['New Deaths'].astype(int)


#select dates (in Y-M-D format)
#dfnew2 = dfnew.loc[dfnew['Date'].between('2020-03-01','2022-02-28', inclusive=True)]
#dfnew2 = dfnew2.reset_index(drop = True)



#convert date back 
dfnew['Date'] = pd.to_datetime(dfnew.Date)
dfnew['UID'] = dfnew['UID'].astype(int)

dfnew

,UID,Date,County,State,Population,Lat,Long,temp,humidity,windspeed,New Deaths,Deaths
0,84001073,2020-03-01,Jefferson,Alabama,658573,33.555547,-86.895063,12.5,44.47,28.8,0,0
1,84001073,2020-03-02,Jefferson,Alabama,658573,33.555547,-86.895063,14.4,85.83,19.0,0,0
2,84001073,2020-03-03,Jefferson,Alabama,658573,33.555547,-86.895063,18.8,82.40,24.0,0,0
3,84001073,2020-03-04,Jefferson,Alabama,658573,33.555547,-86.895063,13.3,90.78,14.5,0,0
4,84001073,2020-03-05,Jefferson,Alabama,658573,33.555547,-86.895063,11.1,89.99,19.4,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
35035,84056021,2022-02-24,Laramie,Wyoming,99500,41.307025,-104.688750,-13.2,68.00,26.9,0,273
35036,84056021,2022-02-25,Laramie,Wyoming,99500,41.307025,-104.688750,-10.6,65.60,21.5,0,273
35037,84056021,2022-02-26,Laramie,Wyoming,99500,41.307025,-104.688750,-6.9,45.00,22.6,0,273
35038,84056021,2022-02-27,Laramie,Wyoming,99500,41.307025,-104.688750,2.5,27.10,37.1,0,273
35039,84056021,2022-02-28,Laramie,Wyoming,99500,41.307025,-104.688750,6.6,23.60,48.7,0,273

In [81]:
dfnew.to_csv(r'C:\Users\Mubby\OneDrive - University of Kentucky\DOCS\SPRING 2022\DS 711\Capstone python\deathdata.csv', index = False)